workflows:
  android-app:
    name: Android App
    environment:
      vars:
        LOCAL_PROPERTIES: "Z0FBQUFBQmZUTXZHZVRSTlVuN3RPcE5BbTR1VFRsLWpwT3lYdXFiOFNBUEpYY0dBUVlpamM0czVBS1pzWm1mV3NyVWlKTHg0ZGpJcFowdlQ5c25MNVdyckoxVWVvSUIwRXNYRVE1VlJLd0RnQnNNQk1lZjlNSFZlRXRwRmM3MkZCc1hxYmdRWkRqVWJkYXZiRzNXVnd3cnNzbHJlT3d4Ull1VUF3OWxJczQ4b01zTTF3OWlGY0JPMjU3azdORVRSZ0RxM1RIbjNQVnRKT3dBcnBQTjdiMFFtbENubzY2QVJrVV93bzJWMGJKd1RBbExTM0NfTWJtRlI1WGlUUHVQNEVjZzZYRTN1SW5JSjlMeEhUcjI4ZE5XMGVPV0xuSWhvTEJtM2pueUJPR1pRV1NNZ0pJUDhfVXhxcG56djhpOHN3bEdBb1VKcy1MQ1NHb0ptMHBhRWlFaHIzb3Z3RmpLRWt0V0M0blJIMlcyVmpCVGtSbEpqeGFXbi1ZUXhobjJPSzFzb1V5NHNKWVRBbmlSYkUwWUxlTDRzU1Z6Nm9MNE90YTE1dkVPYWNYTGNmVU1PYW9pOVB3UkJndVBBVG9ZTDdBbEN3NGNQU0pvcW9lX1o2Nm1qOEJHRnV1XzhicEx2VE5kTFI5U2lubF9jUWtZUThlazdQNjRPVC1NQ2tNaV9VRGxUMEMyckl1NjJ6ekhXY3BabzBmaVpTYzFjT3lpcjVkX0w3amlfX2htOGtWNzh2VTNRVFNBODVIbUMwajBkaTZJMUNTNzFWd1B2TmljTUxHOXRvMGU2N3dPNG9Od2M3dkpLNll0OUNBVGlFR3Z6eHByT1lFckVlVmRFUUtZT1JQNmNfUW10MWFJNGNiUmhyR01tWUtpLWRxTGgyaVhodTRPVDZQMmN2U055WHVMRFpla3hPWlBZSDdSYTRZR1dPeEZ2SFBJLVhYOHNibXltZVluSE1jU1A4aEdQRVNUWHRldHVRa2NFSWFIaEwzYWN4WlUxdERILVVZRnFpaHF3aXlJRkJuNFQ5bGpw"
    scripts:
      - emulator -avd emulator > /dev/null 2>&1 &
      - sleep 45
      - echo $LOCAL_PROPERTIES | base64 --decode > local.properties
      - ./gradlew test
      - ./gradlew connectedCheck
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/reports/**/*.*
